### ISSUE TITLE
README.md specifies incorrect usage for trace (maybe just a typo)

### ISSUE THREAD

**Issue by rpfarish** [elliottkobelansky/dlin#1]
I was testing out the module and tried to have it trace a scramble. However, when I tried it out with the recommended usage with 
"from dlin import tracer" and "described_cycles = tracer("F' L2 B2 F2 D' F2 D F2 U R2 U' L' B L' R' F2 R2 B2 U2 Fw'")" this was the result:
"Traceback (most recent call last):  File "<stdin>", line 1, in <module> TypeError: 'module' object is not callable."

So, I think that "tracer" is a module and not a function, so it is not callable. I did find however that the function "trace" which was instantiated in dlin/__init__.py and is assumedly the intended object to call.
I think then that this is what you meant instead:
from dlin import trace
described_cycles = trace("F' L2 B2 F2 D' F2 D F2 U R2 U' L' B L' R' F2 R2 B2 U2 Fw'")

Unless semantically speaking you like the name "tracer" better but this is how I got it to work.
Also, calling "dlin-trace [scramble]" works fine for me

**Comment by elliottkobelansky** [comment]
It was a typo indeed
